import Seo from "@/components/Seo";

const Privacy = () => (
  <main className="container mx-auto max-w-3xl px-4 py-12 text-foreground">
    <Seo
      title="Privacy Policy | Africa Scout Pulse"
      description="How Africa Scout Pulse collects, uses, and protects your data."
    />
    <h1 className="font-display text-3xl mb-6">Privacy Policy</h1>
    <p className="text-sm text-muted-foreground mb-8">Last updated: June 18, 2026</p>

    <section className="space-y-6 text-sm leading-relaxed">
      <div>
        <h2 className="font-display text-xl mb-2">1. Data we collect</h2>
        <p>
          Account email, authentication identifiers, watchlist selections, feature
          requests, subscription state, and analytics events generated by your use
          of the platform.
        </p>
      </div>

      <div>
        <h2 className="font-display text-xl mb-2">2. How we use it</h2>
        <p>
          To operate authentication, deliver the intelligence terminal, process
          subscription payments via PayPal or Paystack, surface personalized
          briefings, and improve platform reliability.
        </p>
      </div>

      <div>
        <h2 className="font-display text-xl mb-2">3. Sub-processors</h2>
        <ul className="list-disc pl-5 space-y-1">
          <li>Supabase (managed via Lovable Cloud) — database, auth, storage</li>
          <li>PayPal — subscription payments</li>
          <li>Paystack — subscription payments for African card holders</li>
          <li>Lovable AI Gateway — AI-powered analysis and chat</li>
        </ul>
      </div>

      <div>
        <h2 className="font-display text-xl mb-2">4. Your rights (GDPR / POPIA)</h2>
        <p>
          You may request an export or deletion of your personal data at any time
          from <a className="underline" href="/settings">Settings</a>, or by emailing
          privacy@africascoutpulse.com. We respond within 30 days.
        </p>
      </div>

      <div>
        <h2 className="font-display text-xl mb-2">5. Retention</h2>
        <p>
          Account data is retained while your account is active. Aggregated,
          anonymized analytics may be retained indefinitely. Payment records are
          retained for 7 years for tax and compliance purposes.
        </p>
      </div>

      <div>
        <h2 className="font-display text-xl mb-2">6. Contact</h2>
        <p>privacy@africascoutpulse.com</p>
      </div>
    </section>
  </main>
);

export default Privacy;
